"""Add home_type and other fields to Pet model

Revision ID: 18c832de774f
Revises: d985577d19c8
Create Date: 2025-11-03 20:01:46.570604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c832de774f'
down_revision = 'd985577d19c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('activity_level', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('time_commitment', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('family_situation', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pets', schema=None) as batch_op:
        batch_op.drop_column('family_situation')
        batch_op.drop_column('time_commitment')
        batch_op.drop_column('experience')
        batch_op.drop_column('activity_level')
        batch_op.drop_column('home_type')

    # ### end Alembic commands ###
