"""Create pets table

Revision ID: d985577d19c8
Revises: 
Create Date: 2025-11-03 19:41:56.393717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd985577d19c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('public_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('species', sa.String(length=30), nullable=False),
    sa.Column('breed', sa.String(length=120), nullable=False),
    sa.Column('age', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('adopted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=True),
    sa.Column('contact_email_override', sa.String(length=120), nullable=True),
    sa.Column('contact_phone_override', sa.String(length=50), nullable=True),
    sa.Column('public_contact', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('pet_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'pet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites')
    op.drop_table('pets')
    op.drop_table('users')
    # ### end Alembic commands ###
